name: check-default

on:
  push:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check default
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check & Report Default
        uses: dieghernan/cran-status-check@main
        with:
          statuses: "ERROR"

      - name: Check & Report with package name
        uses: dieghernan/cran-status-check@main
        with:
          package: mapSpain
          statuses: "ERROR"
          
      - name: Check & Report with dir
        uses: dieghernan/cran-status-check@main
        with:
          path: testpak
