name: CRAN Status Monitor - OK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cran-status-ok:
    name: Check & Report
    uses: dieghernan/ga-sandbox/cran-status@main
    